apiVersion: apps/v1
kind: Deployment
metadata:
  name: libro-create
spec:
  replicas: 3
  selector:
    matchLabels:
      app: libro-create
  template:
    metadata:
      labels:
        app: libro-create
    spec:
      containers:
      - name: libro-create
        image: rflorezeam/libro-create:sha-d788d5b
        ports:
        - containerPort: 8081
        env:
        - name: MONGODB_URI
          value: mongodb://root:example@libro-mongodb:27017